### ISSUE TITLE
Plugin is broken in 1.20.6

### ISSUE THREAD

**Issue by BlitzOffline** [darbyjack/VoteParty#112]
Spigot changed a lot of org.bukkit.Particle names in 1.20.5 and 1.20.6 to match the Minecraft names.

Some particles that were changed are directly used in code, code that is loaded on plugin enable. This leads to a runtime error and the plugin disabling itself: 
```
[23:22:37 ERROR]: Error occurred while enabling VoteParty v2.38 (Is it up to date?)
java.lang.NoSuchFieldError: Class org.bukkit.Particle does not have member field 'org.bukkit.Particle SPELL_MOB_AMBIENT'
        at VoteParty-2.38.jar/me.clip.voteparty.version.VersionHookNew.<clinit>(VersionHookNew.kt:76) ~[VoteParty-2.38.jar:?]
        at VoteParty-2.38.jar/me.clip.voteparty.VoteParty.loadHook(VoteParty.kt:242) ~[VoteParty-2.38.jar:?]
        at VoteParty-2.38.jar/me.clip.voteparty.VoteParty.load(VoteParty.kt:79) ~[VoteParty-2.38.jar:?]
        at VoteParty-2.38.jar/me.clip.voteparty.plugin.VotePartyPlugin.onEnable(VotePartyPlugin.java:17) ~[VoteParty-2.38.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:22:37 INFO]: [VoteParty] Disabling VoteParty v2.38
```

Here is a list of the particle name changes from 1.20.4 to 1.20.5 compiled by a community member in the PaperMC discord server: https://paste.helpch.at/zupoceqimi.rust

**Comment by darbyjack** [comment]
A user in the Discord has confirmed that https://github.com/darbyjack/VoteParty/commit/843e14aa24443c3336ba45cc5a34b4de347bc887 fixes this.
